/**
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Alerts".equalsIgnoreCase(className)) {
      return new TypeToken<List<Alerts>>(){}.getType();
    }
    
    if ("AlertsAlert".equalsIgnoreCase(className)) {
      return new TypeToken<List<AlertsAlert>>(){}.getType();
    }
    
    if ("ArrayOfSearch".equalsIgnoreCase(className)) {
      return new TypeToken<List<ArrayOfSearch>>(){}.getType();
    }
    
    if ("Astronomy".equalsIgnoreCase(className)) {
      return new TypeToken<List<Astronomy>>(){}.getType();
    }
    
    if ("AstronomyAstro".equalsIgnoreCase(className)) {
      return new TypeToken<List<AstronomyAstro>>(){}.getType();
    }
    
    if ("Current".equalsIgnoreCase(className)) {
      return new TypeToken<List<Current>>(){}.getType();
    }
    
    if ("CurrentAirQuality".equalsIgnoreCase(className)) {
      return new TypeToken<List<CurrentAirQuality>>(){}.getType();
    }
    
    if ("CurrentCondition".equalsIgnoreCase(className)) {
      return new TypeToken<List<CurrentCondition>>(){}.getType();
    }
    
    if ("Error400".equalsIgnoreCase(className)) {
      return new TypeToken<List<Error400>>(){}.getType();
    }
    
    if ("Error401".equalsIgnoreCase(className)) {
      return new TypeToken<List<Error401>>(){}.getType();
    }
    
    if ("Error403".equalsIgnoreCase(className)) {
      return new TypeToken<List<Error403>>(){}.getType();
    }
    
    if ("Forecast".equalsIgnoreCase(className)) {
      return new TypeToken<List<Forecast>>(){}.getType();
    }
    
    if ("ForecastAstro".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastAstro>>(){}.getType();
    }
    
    if ("ForecastCondition".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastCondition>>(){}.getType();
    }
    
    if ("ForecastDay".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastDay>>(){}.getType();
    }
    
    if ("ForecastDayCondition".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastDayCondition>>(){}.getType();
    }
    
    if ("ForecastForecastday".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastForecastday>>(){}.getType();
    }
    
    if ("ForecastHour".equalsIgnoreCase(className)) {
      return new TypeToken<List<ForecastHour>>(){}.getType();
    }
    
    if ("Ip".equalsIgnoreCase(className)) {
      return new TypeToken<List<Ip>>(){}.getType();
    }
    
    if ("Location".equalsIgnoreCase(className)) {
      return new TypeToken<List<Location>>(){}.getType();
    }
    
    if ("Marine".equalsIgnoreCase(className)) {
      return new TypeToken<List<Marine>>(){}.getType();
    }
    
    if ("MarineForecastday".equalsIgnoreCase(className)) {
      return new TypeToken<List<MarineForecastday>>(){}.getType();
    }
    
    if ("MarineHour".equalsIgnoreCase(className)) {
      return new TypeToken<List<MarineHour>>(){}.getType();
    }
    
    if ("Search".equalsIgnoreCase(className)) {
      return new TypeToken<List<Search>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Alerts".equalsIgnoreCase(className)) {
      return new TypeToken<Alerts>(){}.getType();
    }
    
    if ("AlertsAlert".equalsIgnoreCase(className)) {
      return new TypeToken<AlertsAlert>(){}.getType();
    }
    
    if ("ArrayOfSearch".equalsIgnoreCase(className)) {
      return new TypeToken<ArrayOfSearch>(){}.getType();
    }
    
    if ("Astronomy".equalsIgnoreCase(className)) {
      return new TypeToken<Astronomy>(){}.getType();
    }
    
    if ("AstronomyAstro".equalsIgnoreCase(className)) {
      return new TypeToken<AstronomyAstro>(){}.getType();
    }
    
    if ("Current".equalsIgnoreCase(className)) {
      return new TypeToken<Current>(){}.getType();
    }
    
    if ("CurrentAirQuality".equalsIgnoreCase(className)) {
      return new TypeToken<CurrentAirQuality>(){}.getType();
    }
    
    if ("CurrentCondition".equalsIgnoreCase(className)) {
      return new TypeToken<CurrentCondition>(){}.getType();
    }
    
    if ("Error400".equalsIgnoreCase(className)) {
      return new TypeToken<Error400>(){}.getType();
    }
    
    if ("Error401".equalsIgnoreCase(className)) {
      return new TypeToken<Error401>(){}.getType();
    }
    
    if ("Error403".equalsIgnoreCase(className)) {
      return new TypeToken<Error403>(){}.getType();
    }
    
    if ("Forecast".equalsIgnoreCase(className)) {
      return new TypeToken<Forecast>(){}.getType();
    }
    
    if ("ForecastAstro".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastAstro>(){}.getType();
    }
    
    if ("ForecastCondition".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastCondition>(){}.getType();
    }
    
    if ("ForecastDay".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastDay>(){}.getType();
    }
    
    if ("ForecastDayCondition".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastDayCondition>(){}.getType();
    }
    
    if ("ForecastForecastday".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastForecastday>(){}.getType();
    }
    
    if ("ForecastHour".equalsIgnoreCase(className)) {
      return new TypeToken<ForecastHour>(){}.getType();
    }
    
    if ("Ip".equalsIgnoreCase(className)) {
      return new TypeToken<Ip>(){}.getType();
    }
    
    if ("Location".equalsIgnoreCase(className)) {
      return new TypeToken<Location>(){}.getType();
    }
    
    if ("Marine".equalsIgnoreCase(className)) {
      return new TypeToken<Marine>(){}.getType();
    }
    
    if ("MarineForecastday".equalsIgnoreCase(className)) {
      return new TypeToken<MarineForecastday>(){}.getType();
    }
    
    if ("MarineHour".equalsIgnoreCase(className)) {
      return new TypeToken<MarineHour>(){}.getType();
    }
    
    if ("Search".equalsIgnoreCase(className)) {
      return new TypeToken<Search>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
