/**
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ForecastAstro {
  
  @SerializedName("sunrise")
  private String sunrise = null;
  @SerializedName("sunset")
  private String sunset = null;
  @SerializedName("moonrise")
  private String moonrise = null;
  @SerializedName("moonset")
  private String moonset = null;
  @SerializedName("moon_phase")
  private String moonPhase = null;
  @SerializedName("moon_illumination")
  private String moonIllumination = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSunrise() {
    return sunrise;
  }
  public void setSunrise(String sunrise) {
    this.sunrise = sunrise;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSunset() {
    return sunset;
  }
  public void setSunset(String sunset) {
    this.sunset = sunset;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMoonrise() {
    return moonrise;
  }
  public void setMoonrise(String moonrise) {
    this.moonrise = moonrise;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMoonset() {
    return moonset;
  }
  public void setMoonset(String moonset) {
    this.moonset = moonset;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMoonPhase() {
    return moonPhase;
  }
  public void setMoonPhase(String moonPhase) {
    this.moonPhase = moonPhase;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMoonIllumination() {
    return moonIllumination;
  }
  public void setMoonIllumination(String moonIllumination) {
    this.moonIllumination = moonIllumination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastAstro forecastAstro = (ForecastAstro) o;
    return (this.sunrise == null ? forecastAstro.sunrise == null : this.sunrise.equals(forecastAstro.sunrise)) &&
        (this.sunset == null ? forecastAstro.sunset == null : this.sunset.equals(forecastAstro.sunset)) &&
        (this.moonrise == null ? forecastAstro.moonrise == null : this.moonrise.equals(forecastAstro.moonrise)) &&
        (this.moonset == null ? forecastAstro.moonset == null : this.moonset.equals(forecastAstro.moonset)) &&
        (this.moonPhase == null ? forecastAstro.moonPhase == null : this.moonPhase.equals(forecastAstro.moonPhase)) &&
        (this.moonIllumination == null ? forecastAstro.moonIllumination == null : this.moonIllumination.equals(forecastAstro.moonIllumination));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sunrise == null ? 0: this.sunrise.hashCode());
    result = 31 * result + (this.sunset == null ? 0: this.sunset.hashCode());
    result = 31 * result + (this.moonrise == null ? 0: this.moonrise.hashCode());
    result = 31 * result + (this.moonset == null ? 0: this.moonset.hashCode());
    result = 31 * result + (this.moonPhase == null ? 0: this.moonPhase.hashCode());
    result = 31 * result + (this.moonIllumination == null ? 0: this.moonIllumination.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastAstro {\n");
    
    sb.append("  sunrise: ").append(sunrise).append("\n");
    sb.append("  sunset: ").append(sunset).append("\n");
    sb.append("  moonrise: ").append(moonrise).append("\n");
    sb.append("  moonset: ").append(moonset).append("\n");
    sb.append("  moonPhase: ").append(moonPhase).append("\n");
    sb.append("  moonIllumination: ").append(moonIllumination).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
