/**
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ForecastAstro;
import io.swagger.client.model.ForecastDay;
import io.swagger.client.model.MarineHour;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MarineForecastday {
  
  @SerializedName("date")
  private Date date = null;
  @SerializedName("date_epoch")
  private Integer dateEpoch = null;
  @SerializedName("day")
  private ForecastDay day = null;
  @SerializedName("astro")
  private ForecastAstro astro = null;
  @SerializedName("hour")
  private List<MarineHour> hour = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDate() {
    return date;
  }
  public void setDate(Date date) {
    this.date = date;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDateEpoch() {
    return dateEpoch;
  }
  public void setDateEpoch(Integer dateEpoch) {
    this.dateEpoch = dateEpoch;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ForecastDay getDay() {
    return day;
  }
  public void setDay(ForecastDay day) {
    this.day = day;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ForecastAstro getAstro() {
    return astro;
  }
  public void setAstro(ForecastAstro astro) {
    this.astro = astro;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MarineHour> getHour() {
    return hour;
  }
  public void setHour(List<MarineHour> hour) {
    this.hour = hour;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarineForecastday marineForecastday = (MarineForecastday) o;
    return (this.date == null ? marineForecastday.date == null : this.date.equals(marineForecastday.date)) &&
        (this.dateEpoch == null ? marineForecastday.dateEpoch == null : this.dateEpoch.equals(marineForecastday.dateEpoch)) &&
        (this.day == null ? marineForecastday.day == null : this.day.equals(marineForecastday.day)) &&
        (this.astro == null ? marineForecastday.astro == null : this.astro.equals(marineForecastday.astro)) &&
        (this.hour == null ? marineForecastday.hour == null : this.hour.equals(marineForecastday.hour));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.date == null ? 0: this.date.hashCode());
    result = 31 * result + (this.dateEpoch == null ? 0: this.dateEpoch.hashCode());
    result = 31 * result + (this.day == null ? 0: this.day.hashCode());
    result = 31 * result + (this.astro == null ? 0: this.astro.hashCode());
    result = 31 * result + (this.hour == null ? 0: this.hour.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarineForecastday {\n");
    
    sb.append("  date: ").append(date).append("\n");
    sb.append("  dateEpoch: ").append(dateEpoch).append("\n");
    sb.append("  day: ").append(day).append("\n");
    sb.append("  astro: ").append(astro).append("\n");
    sb.append("  hour: ").append(hour).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
